In [5]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])

print(a)
print(np.sum(a,axis=0)) # [5 7 9]

print(np.sum(a,axis = 1)) # [ 6 15]

print(np.sum(a))# 计算所有的值的和

[[1 2 3]
 [4 5 6]]
[5 7 9]
[ 6 15]
21


In [6]:
#三维的数据
a = np.arange(27).reshape((3,3,3))
print(a)

b = np.sum(a, axis=0) #列
print(b)

c = np.sum(a, axis=1) #行
print(c)

d = np.sum(a, axis=2) #组
print(d)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[[27 30 33]
 [36 39 42]
 [45 48 51]]
[[ 9 12 15]
 [36 39 42]
 [63 66 69]]
[[ 3 12 21]
 [30 39 48]
 [57 66 75]]


In [7]:
#数组的索引和切片
import numpy as np

a = np.arange(10)
# print(a)
# 冒号分隔切片参数 start:stop:step 来进行切片操作
# print(a[2:9:2])# 从索引 2 开始到索引 7 停止，间隔为 2

# # 如果只放置一个参数，如 [2]，将返回与该索引相对应的单个元素
print(a[2],a)

# # 如果为 [2:]，表示从该索引开始以后的所有项都将被提取
print(a[2:])

2 [0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6 7 8 9]


In [8]:
#多维数组操作方法
import numpy as np
t1 = np.arange(24).reshape(4,6)
print(t1)
# print('*'*20)
# print(t1[1]) # 取一行(一行代表是一条数据，索引也是从0开始的)
# print(t1[1,:]) # 取一行[行][列]
#取出连续的多行
# print(t1[1:])
# print(t1[1:3,:])#取出连续多行

#取出不连续多行
# print(t1[[0,2,3]])

# print(t1[[0,2,3],:])
#取一列
# print(t1[:,1])
#连续多列
# print(t1[:,1:])
#取出不连续的多列
# print(t1[:,[0,2,3]])#[:行:,:列:]
#取出某一个值(3行4列)
# print(t1[2,3])
#取出多个不连续的值3个值[行,行,行][列,列,列]
print(t1[[0,1,1],[0,1,3]])    

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[0 7 9]


In [6]:
import numpy as np
t = np.arange(24).reshape(4,6)
print(t)
# 修改某一行的值
# t[1,:]=0

# # 修改某一列的值
# t[:,1]=0

# # 修改连续多行
# t[1:3,:]=0

# # 修改连续多列
# t[:,1:4]=0

# # 修改多行多列，取第二行到第四行，第三列到第五列
# t[1:4,2:5]=0

# # 修改多个不相邻的点
# t[[0,1],[0,3]]=5

# # 可以根据条件修改，比如讲小于10的值改掉
# t[t<10]=0
# print(t)

# t[(t>2)&(t<6)]=0   # 与
# t[(t<2)|(t>6)]=0   # 或
# t[~(t>6)]=0   # 非
# print(t)

# 拓展
# 三目运算（ np.where(condition, x, y)满足条件(condition)，输出x，不满足输出y。)）
score = np.array([[80,88],[82,81],[75,81]])
result = np.where(score>80,True,False)
print(result)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[False  True]
 [ True  True]
 [False  True]]


In [11]:
# --------数组的添加删除去重-----------
a = np.array([[1,2,3],[4,5,6]])
 
print ('第一个数组：')
print (a)
print ('\n')
 
print ('向数组添加元素：')
print (np.append(a, [7,8,9]))
print ('\n')

print ('沿轴 0 添加元素：')
print (np.append(a, [[7,8,9]],axis = 0))
print ('\n')

print ('沿轴 1 添加元素：')
print (np.append(a, [[5,5,5],[7,8,9]],axis = 1))
 

第一个数组：
[[1 2 3]
 [4 5 6]]


向数组添加元素：
[1 2 3 4 5 6 7 8 9]


沿轴 0 添加元素：
[[1 2 3]
 [4 5 6]
 [7 8 9]]


沿轴 1 添加元素：
[[1 2 3 5 5 5]
 [4 5 6 7 8 9]]


In [15]:
a = np.array([[1,2],[3,4],[5,6]])
 
print ('第一个数组：')
print (a)
print ('\n')
 
print ('未传递 Axis 参数。 在插入之前输入数组会被展开。')
print (np.insert(a,3,[11,12]))
print ('\n')
print ('传递了 Axis 参数。 会广播值数组来配输入数组。')

print ('沿轴 0 广播：')
print (np.insert(a,2,[11],axis = 0))
print ('\n')
print ('沿轴 1 广播：')
print (np.insert(a,1,11,axis = 1))

第一个数组：
[[1 2]
 [3 4]
 [5 6]]


未传递 Axis 参数。 在插入之前输入数组会被展开。
[ 1  2  3 11 12  4  5  6]


传递了 Axis 参数。 会广播值数组来配输入数组。
沿轴 0 广播：
[[ 1  2]
 [ 3  4]
 [11 11]
 [ 5  6]]


沿轴 1 广播：
[[ 1 11  2]
 [ 3 11  4]
 [ 5 11  6]]


In [17]:
a = np.arange(12).reshape(3,4)
 
print ('第一个数组：')
print (a)
print ('\n')
 
print ('未传递 Axis 参数。 在删除之前输入数组会被展开。')
print (np.delete(a,5))
print ('\n')
 
# print ('删除每一行中的第二列：')
print (np.delete(a,1,axis = 1))
print ('\n')

第一个数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


未传递 Axis 参数。 在删除之前输入数组会被展开。
[ 0  1  2  3  4  6  7  8  9 10 11]


[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]




In [22]:
# 数组去重
a = np.array([5,2,6,2,7,5,6,8,2,9])
 
print ('第一个数组：')
print (a)
print ('\n')
 
print ('第一个数组的去重值：')
u = np.unique(a)
print (u)
print ('\n')

print ('去重数组的索引数组：')
u,indices = np.unique(a, return_index = True)
print(u)
print (indices)
print ('\n')
 
print ('去重数组的下标：')
u,indices = np.unique(a,return_inverse = True)
print (u)
print (indices)
print ('\n')

print ('返回去重元素的重复数量：')
u,indices = np.unique(a,return_counts = True)
print (u)
print (indices)

第一个数组：
[5 2 6 2 7 5 6 8 2 9]


第一个数组的去重值：
[2 5 6 7 8 9]


去重数组的索引数组：
[2 5 6 7 8 9]
[1 0 2 4 7 9]


去重数组的下标：
[2 5 6 7 8 9]
[1 0 2 0 3 1 2 4 0 5]


返回去重元素的重复数量：
[2 5 6 7 8 9]
[3 2 2 1 1 1]


In [46]:
import numpy as np
score = np.array([[80,88],[82,81],[75,81]])

result = np.max(score)
# print(result)

result = np.max(score,axis = 1)
# print(result)

result = np.min(score)
# print(result)

result = np.min(score,axis = 0)
# print(result)

result = np.mean(score)
# print(result)
result = np.mean(score,axis = 1)
# print(result)

#返回给定axis累计和
arr = np.array([[1,2,3],[4,5,6]])
print(arr.cumsum(0))  
print(arr.cumsum(1)) 

# argmin求最小索引
result = np.argmin(score,axis=1)
print(result)

# 标准差
result = np.std(score,axis=0)
print(result)

#极值 最大值和最小值的差
print(np.ptp(score))

[[1 2 3]
 [5 7 9]]
[[ 1  3  6]
 [ 4  9 15]]
[0 1 0]
[2.94392029 3.29983165]
13


In [47]:
# 1. 根据轴连接的数组序列
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
 
# 要求a,b两个数组的维度相同
print ('沿轴 0 连接两个数组：')
print (np.concatenate((a,b),axis= 0))
print ('\n')
print ('沿轴 1 连接两个数组：')
print (np.concatenate((a,b),axis = 1))

沿轴 0 连接两个数组：
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


沿轴 1 连接两个数组：
[[1 2 5 6]
 [3 4 7 8]]


In [54]:
# 数组的分割
arr = np.arange(9).reshape(3,3)
b= np.split(arr,3)
print(b)

harr = np.floor(10*np.random.random((2,6)))
print('原array:',harr)
print('拆分后:',np.vsplit(harr,2))

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]
原array: [[7. 8. 3. 2. 9. 4.]
 [6. 5. 2. 8. 2. 9.]]
拆分后: [array([[7., 8., 3., 2., 9., 4.]]), array([[6., 5., 2., 8., 2., 9.]])]


In [55]:
# 创建一个nan和inf
a = np.nan
b = np.inf
print(a,type(a))
print(b,type(b))

# # --判断数组中为nan的个数(注意：float类型的数据才能赋值nan)
t = np.arange(24,dtype=float).reshape(4,6)
print(t)

#nan数据进行操作的 (nan--->0 nan --->平均值)
# 可以使用np.count_nonzero() 来判断非零的个数
# print(np.count_nonzero(t))

# # 将三行四列的数改成nan
t[3,4] = np.nan
print(t)
# nan 和nan 不相等
# 并且 np.nan != np.nan  结果 是TRUE

# # 所以我们可以使用这两个结合使用判断nan的个数
print(np.count_nonzero(t != t))
t[np.isnan(t)]=0
# print(t)
#注意:任何数与nan计算都是nan
print(np.sum(t,axis=0))

nan <class 'float'>
inf <class 'float'>
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. nan 23.]]
1
[36. 40. 44. 48. 30. 56.]


In [59]:
#----------练习： 处理数组中nan
t = np.arange(24).reshape(4,6).astype('float') 
# 将数组中的一部分替换nan(故意做假数据)
t[1,3:] = np.nan
print(t)
# 遍历每一列，然后判断每一列是否有nan
#6
print(t.shape[1])

for i in range(t.shape[1]):
    #获取当前列数据
    temp_col = t[:,i]
    print(temp_col)

    # 判断当前列的数据中是否含有nan
    nan_num = np.count_nonzero(temp_col != temp_col) 

    if nan_num != 0: # 条件成立说明含有nan

#         # 将这一列不为nan的数据拿出来
        temp_col_not_nan = temp_col[temp_col==temp_col]
        print(temp_col_not_nan)
        # 将nan替换成这一列的平均值
        temp_col[np.isnan(temp_col)] = np.mean(temp_col_not_nan)

print(t)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. nan nan nan]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]
6
[ 0.  6. 12. 18.]
[ 1.  7. 13. 19.]
[ 2.  8. 14. 20.]
[ 3. nan 15. 21.]
[ 3. 15. 21.]
[ 4. nan 16. 22.]
[ 4. 16. 22.]
[ 5. nan 17. 23.]
[ 5. 17. 23.]
[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8. 13. 14. 15.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]]


In [61]:
#对换数组的维度

a = np.arange(12).reshape(3,4)
 
print ('原数组：')
print (a )
print ('\n')

print ('对换数组：')
print (np.transpose(a))

# 与transpose一致
a = np.arange(12).reshape(3,4)
print ('原数组：')
print (a)
print ('\n')
 
print ('转置数组：')
print (a.T)

原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


对换数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
原数组：
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


转置数组：
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [62]:
import numpy as np
# 函数用于交换数组的两个轴
t1 = np.arange(24).reshape(4,6)
re = t1.swapaxes(1,0)
print ('原数组：')
print (t1)
print ('\n')

print ('调用 swapaxes 函数后的数组：')
print (re)

原数组：
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


调用 swapaxes 函数后的数组：
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]
